services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/whistify-scores
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - ALLOWED_HOSTS=milandp.be
    ports:
      - "4173:4173"

volumes:
  mongo_data:
